version: '3.9'
services:
  web:
    image: mathmagicmachine/pythonprimer_web
    build: .
    command: python3 manage.py runserver 127.0.0.1:8000
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres