version: "3.9.12"
services:
  web:
    build: .
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes:
      - .:.
    ports:
      - "80:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres