# Generated by Django 4.0.3 on 2022-04-09 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0002_rename_comment_comment_content_remove_channel_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
