# Generated by Django 4.0.3 on 2022-04-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0003_alter_video_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, upload_to='Videos/Channels/banners/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='watch/Videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='watch/Videos/Thumbnails/'),
        ),
    ]
