# Generated by Django 4.0.4 on 2022-04-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0005_video_created_at_video_updated_at_alter_channel_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='updated_at',
        ),
    ]
