# Generated by Django 4.0.3 on 2022-04-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0010_playlist_created_at_playlist_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='uuid',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
